# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    sudo apt install gdb libx11-dev libxrandr-dev libxi-dev libxv-dev libcups2-dev libxdamage-dev libxcursor-dev libxext-dev libxinerama-dev libxkbcommon-dev libxkbfile-dev libxml2-dev libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libpulse-dev libpcsclite-dev libgsm1-dev libavcodec-dev libavutil-dev libx264-dev libxext-dev
  displayName: 'install dependencies'

- script: |
    cmake -G "Unix Makefiles" -C ci/cmake-preloads/config-linux-all.txt -D CMAKE_BUILD_TYPE=Debug -DWITH_LIBSYSTEMD=OFF -DWITH_WAYLAND=OFF .
    make
  displayName: 'make'